language: cpp
dist: trusty
compiler:
- g++
addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
os:
- linux
before_script:
- git clone https://github.com/dtschump/CImg.git CImg_lib
- mv CImg_lib/CImg.h CImg.h
script: make
branches:
  only:
  - master
  - "/^v\\d+\\./"
notifications:
  email: true